### ISSUE TITLE
Unable to load data while using sam-datatable(Contract Opportunities reports) after Angular 12 upgrade

### ISSUE THREAD

**Issue by pulichinthala525** [GSA/sam-ui-elements#543]
We are unable to load the data while using sam-datatable 
We have an issue after updating to Angular 12
sam-datatable is not supporting with Angular 12,
I have used package.json on integration-38.2 it works with angular 11
So we have compatibility issue for sam-datable with Anugular 12
https://github.com/GSA/sam-ui-elements/blob/master/src/ui-kit/components/data-table/data-table.component.ts

We have two issues with sam-datatable 

- Saved functionality on Standard reports 
- Contract Opportunities Reports 
Below link for files used for above issue in our code base
https://github.helix.gsa.gov/GSA-IAE-APPS/sam-front-end/blob/develop/src/app/Reports/sections/overview/overview.template.html
https://github.helix.gsa.gov/GSA-IAE-APPS/sam-front-end/blob/develop/src/app/databank/report/databank.page.html

![image](https://user-images.githubusercontent.com/102316444/160176147-3b41efcc-6097-4ec5-9a41-3496c936b12a.png)
![image](https://user-images.githubusercontent.com/102316444/160177335-e16f3148-5e6a-4d20-b658-d030b91695f2.png)

**Comment by yerramshilpa** [comment]
@pulichinthala525 this working fine in the sam-design-system-site application, this one doesnot have any issues loading the data 

https://federalist-ec570dca-3d1b-4f47-ba04-527773adb448.app.cloud.gov/preview/gsa/sam-design-system-site/angular-12/patterns/page/layout


https://github.com/GSA/sam-design-system-site/blob/angular-12/src/patterns/pages/layout/layout-nosidebar.template.html

**Comment by pulichinthala525** [comment]
This is working since it has as "@angular/cdk": "^10.2.7",
If I update this to current version which sam-front-end has "@angular/cdk": "12.2.13", 
Even sam-design-system-site unable to load data  as shown below  
![image](https://user-images.githubusercontent.com/102316444/160483132-da9d3b50-ccab-45a5-9d83-7a244e80c1d8.png)

**Comment by yerramshilpa** [comment]
New version released @gsa-sam/sam-ui-elements@4.0.3
