### ISSUE TITLE
sam-datatable broken with Angular 17

### ISSUE THREAD

**Issue by flacks** [GSA/sam-ui-elements#556]
Hi team,

sam-datatable seems to be failing with the SFE upgrade to Angular 17.3.6 (including CDK). It no longer displays at all in several sections of SFE, and seems to throw a `No provider for InjectionToken CDK_TABLE`. Please let me know if you need additional info.

**Comment by yerramshilpa** [comment]
We are not able to reproduce the issue in our documentation, here is the link https://gsa.github.io/sam-design-system-site/ 
Goto to pattern and select any data table

**Comment by yerramshilpa** [comment]
@flacks The issue has been resolved in @gsa-sam/sam-ui-elements@17.0.2 version.

**Comment by flacks** [comment]
Thank you so much, will test today and close if resolved!

**Comment by flacks** [comment]
Confirmed, working. Thank you once again!
